name: 🚧 디자인 작업
description: 하나의 디자인 작업 단위를 기록하고 공유하기 위해 사용합니다.
title: "🚧 Design. "
labels: ["Design-WIP"]
assignees: []

body:
  - type: textarea
    id: goal
    attributes:
      label: 🎯 목적 및 작업 배경
      placeholder: 이 작업이 왜 필요한지, 어떤 문제를 해결하려는지 설명해주세요.
    validations:
      required: true

  - type: textarea
    id: task
    attributes:
      label: 📌 작업 내용
      placeholder: 어떤 디자인 작업을 수행해야 하는지 구체적으로 작성해주세요. (예: UI 컴포넌트 디자인, 화면 플로우 확정 등)
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: 📋 체크리스트
      options:
        - label: "와이어프레임/플로우 설계"
        - label: "UI 디자인"
        - label: "내부 피드백 반영"
        - label: "디자인 시스템 작업"
        - label: "개발 전달용 정리"
        - label: "조사 및 리서치 관련 작업"
        - label: "3D 에셋 제작 관련 작업"

  - type: textarea
    id: output
    attributes:
      label: 🖼️ 결과물 링크
      placeholder: Figma, Notion, Drive 링크 등을 첨부해주세요.
    validations:
      required: false
      
  - type: textarea
    id: screenshot
    attributes:
      label: 🖼 스크린샷 또는 로그
      placeholder: 예) Xcode 콘솔 로그 첨부 또는 에러 화면
    validations:

  - type: input
    id: due
    attributes:
      label: 📅 Due Date
      placeholder: YYYY-MM-DD
    validations:
      required: false
